:imagesdir: img
= Logical Network Layout

This document describes the configuration of the active network components.

== https://en.wikipedia.org/wiki/Stackable_switch[Stacking]

To provide building-to-building connectivity, we use the stacking features of the DGS-3130 series switches. Those switches have 10GBit ports that can be put into a special mode, where they function as a transparent bus between up to 9 switches of that series.

The set of switches connected in that way is referred to as a stack. From the administrators point of view, the switches participating in a stack can be configured as one entity, by connecting to the designated master switch only. The port addressing includes not only the port number, but also the stack ID of the switch they belong to. This ID is configured explicitly before adding a switch to the stack.

|===
h|Stack ID  h|Location                  h|Stack Priority    h|Linked Switches (Stack ID)
|1          .2+|Local Elec C (Tines 5C) |TBD                |4,2
|2                                      |TBD                |1,7
|4          .2+|Local Elec A (Tines 3C) |TBD                |1,5
|5                                      |TBD                |4,7
|7          |Local Elec B (Tines 1)     |TBD                |2,5
|===

== Virtual Local Area Networks (https://en.wikipedia.org/wiki/Virtual_LAN[VLANs])

To isolate devices and allow only specific communication relations, while installing only a minimum of physical links (thus reducing costs), it is common practice to define so-called VLANs.

The simplest implementation of this concept is to assign specific switch ports to logical https://en.wikipedia.org/wiki/Data_link_layer[layer 2] local networks. Only ports assigned to the same logical network (VLAN) are visible to each other. To distinguish those VLANs, they are identified by numbers (VLAN IDs).

More advanced concepts exist, to simplify the configuration of typical application scenarios and network topologies. We use two of those, that are implemented by D-Link managed switches:

* https://eu.dlink.com/uk/en/support/faq/switches/layer-2-gigabit/dgs-series/es_dgs_1510_asymmetric_vlan_red_corporativa_e_invitados[Asymmetric VLAN] (DGS-1210 series)
* https://www.geeksforgeeks.org/private-vlan/[Private VLAN] (DGS-3130 series)

Both variants allow connectivity between two sets of ports but without implicitly connecting the ports within one of those sets. This is sometimes called the "hotel setup".

=== VLAN ID assignment

Packets are assigned to specific VLANs by 'tagging' them with a special layer 2 packet header, containing the VLAN ID. In most cases, this happens when untagged ("normal") packets enter a specific switch port that is configured as an "access" or "host" port. They carry that VLAN ID when passing though the switch fabric but loose them as soon as they exit the switch via another access port.

Switch ports can also be configured as https://www.practicalnetworking.net/stand-alone/vlans/["trunk" ports]. Those ports only accept or output tagged packets, untouched. That way they can travel to another switch or router, where they are still identifiable with respect to the VLAN they belong to.

=== VLAN IDs

Derived from our physical network layout and the need to effectively separate most devices from each other, we define VLAN IDs as follows:

|===
h|VLAN ID h|Purpose

|1
|*default:* inter-switch protocols, administration (only)

|100
|*technical monitoring:* uplink to modem with 13 static public IPs { IP~P0~ .. IP~P12~ }, also including masquerading NAT + DHCP router

|20__n__
|*technical monitoring:* devices configured for public static IP~P__n__~ with __n__ = { 1 .. 12 }

|4__nn__
|*technical monitoring:* devices in separate DHCP enabled IPv4 subnets behind masquerading NAT + DHCP router

|1000, 2000 footnote:[during provider transition, using two equivalent private VLANs in parallel]
|*shared internet:* uplink to modem / router for community uplink with public dynamic IP / primary of private VLAN

|1100, 2100
|*shared internet:* all rooms eligible for community access / isolated of private VLAN

|1200, 2200
|*shared internet:* common areas, community of private VLAN (for mesh WiFi etc.)

|===

=== Private (dynamic) IP subnets and VLAN IDs for technical monitoring

To isolate the DHCP-assigned monitoring devices, each gets its own address range in its own subnet. For simplicity and maximum compatibility, we use class-C subnets even though they only need a single address. The gateway (Edge Router X) has the `.1` address in each subnet. The range reserved for DHCP starts from `.128`.

|===
h|Device                      h|IP subnet         h|VLAN ID
|Neovac MCR C                 |192.168.10.0/24    |410
|Neovac MCR B                 |192.168.11.0/24    |411
|Neovac MCR A1                |192.168.12.0/24    |412
|Neovac MCR A3                |192.168.13.0/24    |413
|Photovoltaique Local Elec C  |192.168.20.0/24    |420
|Photovoltaique Local Elec B  |192.168.21.0/24    |421
|Photovoltaique Local SIN B   |192.168.22.0/24    |422
|Photovoltaique Local Elec A  |192.168.23.0/24    |423
|Temporary / internal use     |192.168.30.0/24    |430
|Sprinkler                    |192.168.40.0/24    |440
|e-mobility Local SIN B       |192.168.50.0/24    |450
|e-mobility WiFi charging bots|192.168.51.0/24    |451
|e-mobility WiFi users        |192.168.52.0/24    |452
|chaudières                   |192.168.60.0/24    |460
|===

=== Private (dynamic) IP subnets and VLAN IDs for connection sharing

|===
h|Device(s) h|IP address/mask h|VLAN ID

|ISP modem iWay
|10.135.0.1/16
|1000

|Subscriber devices iWay
a|10.135.0.0/16

_DHCP => 10.135.32.1 ... 10.135.255.254_
|1100, 1200

|ISP ONT Init7
|10.133.0.1/16
|2000

|Subscriber devices Init7
a|10.133.0.0/16

_DHCP => 10.133.32.1 ... 10.133.255.254_
|2100, 2200                                     
|===

=== Management and services

|===
h|Device(s)           h|Location                    h|IP address/mask   h|VLAN ID
|ISP modem            .5+|Local Elec C (Tines 5C)   |10.135.0.1/16      |1000
|DGS-3130 Stack ID 1                                |10.134.0.1/24      .8+|1
|DGS-3130 Stack ID 2                                |10.134.0.2/24
|DGS-1210-16                                        |10.134.0.151/24
|Edge Router X                                      |10.134.0.152/24
|DGS-3130 Stack ID 4  .6+|Local Elec A (Tines 3C)   |10.134.0.4/24
|DGS-3130 Stack ID 5                                |10.134.0.5/24
|DGS-1210-16                                        |10.134.0.131/24
.3+|Authserver                                      |10.134.0.132/24
                                                    .2+|10.135.1.1/16   |1000
                                                                        |1100
|DGS-3130 Stack ID 7  .2+|Local Elec B (Tines 1)    |10.134.0.7/24      .4+|1
|DGS-1210-16                                        |10.134.0.111/24
|RB260GSP             |Local SIN B                  |DHCP check on Edge Router X. (legacy 10.134.0.132/24)
|DAP-2610             |Parking                      |10.134.0.133/24
|===

=== User Authentication

A centralized Authserver is available to manage VPN users and 802.1X authentication. This server is available in the management VLAN (to authenticate VPN users) and in the private VLANs of the shared connection (for WPA2-Enterprise access). It has multiple logical interfaces for its single physical connector.

The DGS-1210-16 port it is connected to is configured for assymmetric VLAN to match the private VLAN setup. It will egress VLAN ID 1 tagged, and VLAN IDs 1000 and 1100 untagged. It will tag any untagged ingress packets with VLAN ID 1000. That way it behaves exactly as an promicious port of the primary VLAN.
