= Switch Setup
:imagesdir: img

This document step by step describes how a current network setup was done on the L3 Layer Switches.
Use a logical_layout.adoc and a physical_layout.adoc documents to understand and reference some setup objects.

== Stacking setup

On the logical_layout.adoc file / Stacking chapter you will find a table with a L3 Switch location, Stacking ID and Priority information.
On the physical_layout.adoc you will find which port(s) is used to interconnect L3 Switches for stacking.
Reference to footnote:[reference to DGS-3130 Series Layer 3 Stackable Managed Switch Web UI Reference Guide] to understand what roles play Master, Backup Master and Slaves.

To be able to administer all L3 Switches, you need to use a MGMT (Management) port on the Master Switch. Use 192.168.0.1 on the Internet Browser to reach L3 Switch GUI Web page.

Before interconnecting L3 Switches physically and enabling Stacking on all of them, it is better to connect to each L3 Switch (later as Switch) via MGMT port and pre-setup Stacking ID and Priority in advance using footnote[1]. That will help to avoid any auto ID and Master assignements.

*Step 1. Setup Stack ID, Priority and enable stacking.*

* Connect to every Switch via MGMT port.
* Go to menu Management > Stacking > Physical Stacking

image::Physical_Stacking_window.svg[opts=inline,width=800]

* On the *Stack ID* chapter on the Current Unit ID drop down box check that you selected a current unit ID (default for new device is 1) and on the New Box ID select a required Unit ID using footnote[1]. And tick Apply.
* On the *Priority* chapter on the Current Unit ID drop down box check that you selected a current unit ID and on the New Priority select a required Priority using footnote[1]. And tick Apply.
Note: a highest priority has a higher priority number. E.g. Master has 12, others < 12.
* On the *Physical Stacking* chapter make a Stacking Mode = Enabled. And tick Apply.

*Step 2. Setup a Stacking Bandwidth.*

* Go to menu *Management > Stacking > Stacking Bandwidth*.
* Select *2-port-SFP+*. And tick Apply.

image::Stacking_Bandwidth_window.svg[opts=inline,width=800]

*Step 3. Reboot Switch(es).*

* Go to Tools > Reboot System menu on top.
* Choose "Do you want to save settings" = Yes.
* Tick Reboot.

*Step 4. Check a Stacking setup.*

* Connect to Master Switch via MGMT port.
* Go to menu *Management > Stacking > Physical Stacking*.
* Check the table.
<insert a real screenshot>
* Check if Master Switch led shows a blinking 1 and H. 'H' means this is a Primary Master.
'h' means an Backup Master. Slaves do not blink and show only stacking number.

== Setup VLANs

Our goal is to separate a private apartments subnetworks and other technical subnetworks.
Refer to the logical_layout.adoc file /  VLAN IDs chapter

* Go to menu *L2 Features > VLAN > 802.1Q VLAN*.
* On the 802.1Q VLAN chapter enter VLAN VID as *1000* and tick Apply.
VID 1000 is used as Primary VLAN for Shared Internet on the Switch port to ISP modem side.
* On the 802.1Q VLAN chapter enter VLAN VID as *1100* and tick Apply.
VID 1100 is used as Isolated VLAN for Shared Internet for all host ports (apartments) side as Private VLAN later.
* Go to vlans table, take e.g. VID 1000, tick on Edit and update the name of that VLAN (VID).

image::802.1Q_VLAN_window.svg[opts=inline,width=800]

== Setup Ports

Hosts + Trunk for Tech Codha.

*Step1.*

Now we need to change a VLAN type of the physical ports configuring a VLAN Interface.

* Connect to Master Switch via MGMT port.
* Go to menu *L2 Features > VLAN > VLAN Interface*.
* Choose a Unit 1 on drop-down box.
* On the Unit 1 Settings table choose port 1 (eth1/0/1) and tick Edit.
* Choose a *VLAN Mode* = *Host*. Leave an Acceptable Frame = Admit All. Leave Ingress Checking = Enabled.
* Enable a Clone box. And choose From Port: eth1/0/1 and To Port: eth1/0/23. That will help to apply the same Host setup on other ports automatically.
* Tick apply.
* Do the same for other Switches, selecting an exact Unit at the previous page on menu L2 Features > VLAN > VLAN Interface. Do the same steps as above.

image::Configure_VLAN_Interface_Host_window.svg[opts=inline,width=800]

*Step2.*

Do the same exercise setting up a Trunk ports.

* Connect to Master Switch via MGMT port.
* Go to menu *L2 Features > VLAN > VLAN Interface*.
* Choose a Unit 1 on drop-down box.
* On the Unit 1 Settings table choose port 24 (eth1/0/24) (this is dedicated for Tech Codha setup) and tick Edit.
* Choose a *VLAN Mode* = *Trunk*. Leave an Acceptable Frame = Admit All. Leave Ingress Checking = Enabled.
* Tick apply.
* Do the same for other Switches, selecting an exact Unit at the previous page on menu L2 Features > VLAN > VLAN Interface.

image::Configure_VLAN_Interface_Trunk_window.svg[opts=inline,width=800]

*Step3.*

Do the same exercise setting up a Host port for ISP modem side/port connection.

* Connect to Master Switch via MGMT port.
* Go to menu *L2 Features > VLAN > VLAN Interface*.
* Choose a Unit 1 on drop-down box.
* On the Unit 1 Settings table choose port 26 (eth1/0/26) and tick Edit.
* Choose a *VLAN Mode* = *Promiscuous*. Leave an Acceptable Frame = Admit All. Leave Ingress Checking = Enabled.
* Tick apply.

== Setup a Private VLAN

Now we need to setup a Private VLAN (PVLAN).

* Connect to Master Switch via MGMT port.
* Go to menu *L2 Features > VLAN > Private VLAN*.
* On the Private VLAN chapter select VID List = 1000, State = Enabled, Type = Primary. Tick Apply.
* On the Private VLAN chapter select VID List = 1100, State = Enabled, Type = Isolated. Tick Apply.
* On the Private VLAN Association chapter select VID = 1000 (this is an uplink to modem VLAN), Action = Add, Secondary VID List = 1100 (this is a flats VLAN). Tick Apply.
* On the Private VLAN Host Association chapter use From Port: eth1/0/1, To Port: eth1/0/23, Primary VID = 1000, Secondary VID = 1100. Tick Apply.
* On the Private VLAN Mapping chapter use From Port: eth1/0/26, To Port: eth1/0/26, Primary VID = 1000, Action = Add, Secondary VID List = 1100. Tick Apply.

image::Private_VLAN_window.svg[opts=inline,width=800]

== Secure VLANs

Remove Shared VLANs from the Trunk (tech Codha) port.
To securely split a Shared Internet and a Tech Codha subnetworks we need to restrict any opposite VLAN visibility.

* Connect to Master Switch via MGMT port.
* Go to menu *L2 Features > VLAN > VLAN Interface*.
* Choose a Unit 1 on drop-down box.
* On the Unit 1 Settings table choose port 24 (eth1/0/24) (this is dedicated for Tech Codha setup) and tick Edit.
* As it was setup above, leave a *VLAN Mode* = *Trunk*. Leave an Acceptable Frame = Admit All. Leave Ingress Checking = Enabled.
* Choose a VLAN (VID), which we need to remove. In our case choose *VID = 1000*, Action = *Remove*
* Tick apply.
* Do the same for VID = 1100.
* Do the same for other Switches, selecting an exact Unit at the previous page on menu L2 Features > VLAN > VLAN Interface.

== Setup DHCP Snooping

Snooping will sniff DHCP communication to track which MAC gets what IP on what port.

* Connect to Master Switch via MGMT port.
* Go to menu *Security > IMPB > IPv4 > DHCPv4 Snooping > DHCP Snooping Global Settings*
* Set "DHCP Snooping" to "Enabled". Tick Apply.
* Go to menu *Security > IMPB > IPv4 > DHCPv4 Snooping > DHCP Snooping VLAN Settings*
* Set *VID List* = *1000* and *State* = *Enabled*. Tick Apply.
* Go to menu *Security > IMPB > IPv4 > DHCPv4 Snooping > DHCP Snooping Port Settings*
* Set *From Port* = *eth1/0/26*
* Set *To Port* = *eth1/0/26*
* Set *Trusted* = *Yes*. Tick Apply.
* Go to menu *Security > IMPB > IPv4 > IP Source Guard > IPv4 Source Guard Port Settings*
* Set *From Port* = *eth1/01*, *To Port* = *eth1/0/23*, *State* = *Enabled*, *Validation* = *IP-MAC*. Tick Apply.
* Repeat the previous step for the other units
** *eth2/0/1* - *eth2/0/24*
** *eth4/0/1* - *eth4/0/23*
** *eth7/0/1* - *eth7/0/23*

image::DHCP_Snooping_Binding_real_tracking_example.svg[opts=inline,width=800]

== Protect router from direct IP connections (configuration interface, UPNP..)

* Connect to Master Switch via Console port (serial cable)
* Enter the follow series of commands, substitute w.x.y.z by internal router IP
----
enable 15
configure terminal
ip access-list nomodem
deny any host w.x.y.z
exit
interface ethernet 1/0/26
ip access-group nomodem out
----
